apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "nginx-k8s-loadbalancer:ingress-resource-get-watch-list"
  namespace: nkl
subjects:
  - kind: ServiceAccount
    name: nginx-k8s-loadbalancer
    namespace: nkl
roleRef:
  kind: ClusterRole
  name: ingress-resource-get-watch-list
  apiGroup: rbac.authorization.k8s.io
