apiVersion: v1
kind: Secret
metadata:
  name: nginx-k8s-loadbalancer-secret
  namespace: nkl
  annotations:
    kubernetes.io/service-account.name: nginx-k8s-loadbalancer
type: kubernetes.io/service-account-token
