# This workflow will build and push a signed Docker image

name: Build and sign image

on:
  # THIS BLOCK IS FOR TESTING
  create:

# THIS BLOCK IS THE ACTUAL DESIRED EVENT TRIGGER
#  pull_request:
#    branches:
#      - "*" # Run on all branches
#    types:
#      - closed   ## This needs to be uncommented after testing

env:
  REGISTRY: docker.io
  IMAGE_NAME: "ciroque/nginx-k8s-loadbalancer" # ${{ github.repository }}

jobs:
  build_and_sign_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919 #v3.0.2
        with:
          cosign-release: 'v1.13.1'

      - name: Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

#      - name: Log into registry ${{ env.REGISTRY }} for ${{ github.actor }}
#        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # NOTE: This runs statically against the latest tag in Docker Hub which was not produced by this workflow
      # This should be updated once this workflow is fully implemented
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        continue-on-error: true
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          format: 'sarif'
          output: 'trivy-results-${{ inputs.image }}.sarif'
          ignore-unfixed: 'true'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@d186a2a36cc67bfa1b860e6170d37fb9634742c7 # v2.2.11
        continue-on-error: true
        with:
          sarif_file: 'trivy-results-${{ inputs.image }}.sarif'
